# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "9ef4da3e-7056-4b95-b2fe-3c98a4c937f8"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build your iOS app
  gym(
    # scheme: "YourScheme",
    export_method: "development"
  )

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "c3cd8e7b8eaef764bdb92f2e31de0cb74bbebb78",
    build_secret: "41efdeeec913651e508a704f24d6615ee7c943a01400711103d2df6487132187"
  )
end

